# docker-compose.yml for local development

version: '3.5'

volumes:
  mysql:
    driver: 'local'

services:
  guardmech:
    image: ghcr.io/acidlemon/guardmech:v0.1.0
    env_file: .env-guardmech
    depends_on: ["mysql"]

  nginx:
    image: nginx
    ports:
      - "4510:80"
    volumes:
      - "./nginx.default.template:/etc/nginx/conf.d/default.template"
    env_file: .env-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on: ["guardmech"]

  dumper_app:
    image: scalify/http-dump
    environment:
      - PORT=8080

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env-mysql

